# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Clang Format
on:
  push:
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: DoozyX/clang-format-lint-action@v0.15
        with:
          source: "."
          exclude: "./build"
          extensions: "h,hpp,c,cc,cpp"
          clangFormatVersion: 15
